-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnai5KzYfCZ2xdNds
yiKOtTnmVfxC2eUcjSbVh1fYwe+gCgYIKoZIzj0DAQehRANCAAS9oEmQTvvCLxRP
qWd42Ek9pLIUU9Hdjg5J5mjmnDJbcrnXkMb75F26/xiTXCYg86JqLg/JYrmMSyeP
K/VLfr9r
-----END PRIVATE KEY-----